### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by andrearosasco** [miccunifi/SEARLE#1]
Hello, first of all, thanks for the great work! 
I'd like to test your method but I can see the code is yet to be released.
Are you planning to release the code?

**Comment by LorenzoAgnolucci** [comment]
HI! Thanks for your interest in our work!

We plan to release the code by the end of June, so keep an eye on this repo!

**Comment by LorenzoAgnolucci** [comment]
Hi @andrearosasco!

We just released all the code and the pre-trained models!

We hope that you will find them helpful to you. If you have any other questions, please feel free to open an issue and we will help you as soon as possible.
