### ISSUE TITLE
Error with the submission format

### ISSUE THREAD

**Issue by baohl00** [miccunifi/SEARLE#10]
Hi, 

I am in struggle with the format of my submission.
[circo_test_mixer.json](https://github.com/user-attachments/files/16726704/circo_test_mixer.json)
I have checked many times and couldn't figure out what's wrong with it. I use the same code to generate this json file. 
Can you have a look with it as I don't know the error is from mine or your evaluation system.

Many thanks.

**Comment by LorenzoAgnolucci** [comment]
Hi @baohl00

Thanks for your interest in our work!

The problem in your file is that at least one query (index 130) has duplicate predictions (i.e. the image with index 297636 compares twice among the retrieved images). 

Hope this helps. Feel free to ask further questions if needed.
