### ISSUE TITLE
Could you share the complete images of FashionIQ dataset ?

### ISSUE THREAD

**Issue by Yang-bug-star** [miccunifi/SEARLE#11]
In the official repository, only 74381 images can be downloaded

**Comment by ABaldrati** [comment]
Hi @Yang-bug-star 

I think you can download the fashioniq dataset using the link in https://github.com/XiaoxiaoGuo/fashion-iq/issues/18 or using the following hugginface datasets repo https://huggingface.co/datasets/Plachta/FashionIQ/tree/main

Let me know if this solves your problem.

**Comment by Yang-bug-star** [comment]
But the link in&nbsp;XiaoxiaoGuo/fashion-iq#18&nbsp;and&nbsp;
https://huggingface.co/datasets/Plachta/FashionIQ/tree/main&nbsp;&nbsp;only contain 74381 images , which is not equal to the original number of images in fashioniq paper


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miccunifi/SEARLE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月27日(星期二) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miccunifi/SEARLE] Could you share the complete images of FashionIQ dataset ? (Issue #11)





 
Hi @Yang-bug-star
 
I think you can download the fashioniq dataset using the link in XiaoxiaoGuo/fashion-iq#18 or using the following hugginface datasets repo https://huggingface.co/datasets/Plachta/FashionIQ/tree/main
 
Let me know if this solves your problem.

**Comment by ABaldrati** [comment]
I don’t recall the exact figures from the FashionIQ paper, but there are a total of 74,381 FashionIQ images, so you should have access to all of them.
Please note that some images fall into multiple categories, so the total number of images **is not** simply the sum of the images in each individual category.

Let me know if this solves your problem.

**Comment by Yang-bug-star** [comment]
By the way, I want to ask that did your reported results in paper are based on validation set of&nbsp;FashionIQ dataset or test set ? Because I see that the original test set doesn't contain ground truth




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "miccunifi/SEARLE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月27日(星期二) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [miccunifi/SEARLE] Could you share the complete images of FashionIQ dataset ? (Issue #11)





 
I don’t recall the exact figures from the FashionIQ paper, but there are a total of 74,381 FashionIQ images, so you should have access to all of them.
 Please note that some images fall into multiple categories, so the total number of images is not simply the sum of the images in each individual category.
 
Let me know if this solves your problem.

**Comment by ABaldrati** [comment]
As a standard practice, we report the results on the validation set of the FashionIQ
