### ISSUE TITLE
Request for fashionIq Dataset

### ISSUE THREAD

**Issue by 0112HY** [miccunifi/SEARLE#12]
Hello, I am a researcher and I am very interested in your work. For my current research, I am missing the FashionIQ dataset, and the dataset I obtained online has missing data. Do you have a way to obtain the complete FashionIQ dataset, or can you provide a link to the FashionIQ dataset? I would be extremely grateful. Thank you.

**Comment by LorenzoAgnolucci** [comment]
Hi @endJavalll,

Please see [this issue](https://github.com/miccunifi/SEARLE/issues/11).
