### ISSUE TITLE
Question abou train_phi.py

### ISSUE THREAD

**Issue by Code-kunkun** [miccunifi/SEARLE#3]
![image](https://github.com/miccunifi/SEARLE/assets/58265850/30f2bb19-38e7-4159-994f-7b67cd655625)
Is there some bugs with this [code?](https://github.com/miccunifi/SEARLE/blob/738b45fb57dbba2207a470af5700c33fbb128ebd/src/train_phi.py#L184C1-L184C1)

**Comment by ABaldrati** [comment]
HI @Code-kunkun 
Sorry for the late reply, during the past weeks, we were on vacation.

Yes, you are right, we made a mistake during the refactoring of our code for the release!
I'll update the code as soon as possible.


Alberto

**Comment by Code-kunkun** [comment]
Thanks for your reply!!!
