### ISSUE TITLE
Location of the right preprocessing function

### ISSUE THREAD

**Issue by NoamSC** [miccunifi/SEARLE#4]
Hi!
When running the Minimal Working Example I encountered the following comment:
# NOTE: the preprocessing function used to train SEARLE is different from the standard CLIP preprocessing function. Here,
# we use the standard one for simplicity, but if you want to reproduce the results of the paper you should use the one
# provided in the SEARLE repository (named targetpad)

Where is the right preprocessing function located?
ty

**Comment by ABaldrati** [comment]
Hi @NoamSC 

Thanks for your interest in our work!!
The preprocess function used to train the textual inversion network is [this one](https://github.com/miccunifi/SEARLE/blob/f47a1be408cafc9734a85ce3219c4230440dc584/src/data_utils.py#L53)

For more info about this preprocess pipeline refer to https://arxiv.org/abs/2308.11485

Kind regards,
Alberto
