### ISSUE TITLE
Imagenet1k Dataset

### ISSUE THREAD

**Issue by jieWANGforwork** [miccunifi/SEARLE#6]
Hi, can I ask how to download Imagenet 1K testset? I could not find the corresponding one you said in the given website. Could you please give some hints for locating this data? Thanks for your help.

**Comment by LorenzoAgnolucci** [comment]
Hi @jieWANGforwork!

Thanks for your interest in our work!

You have to register in the ImageNet [official site](https://image-net.org/download.php) reported in the README of our repo. Then you have to click on "Download" (in the navbar) -> "2012" (under the "ImageNet Large-scale Visual Recognition Challenge (ILSVRC)" section) -> "Test images (all tasks)" (under the "Images" section).
