### ISSUE TITLE
Can you tell me where to download cap.rc2.[train | val | test1].json and split.rc2.[train | val | test1].json for the CIRR dataset? I can only download the raw images from the given links.

### ISSUE THREAD

**Issue by lz75258** [miccunifi/SEARLE#7]

**Comment by LorenzoAgnolucci** [comment]
Hi @lz75258!

Thanks for your interest in our work!

The instructions for downloading the ```json``` files you mentioned are reported in the [corresponding section](https://github.com/Cuberick-Orion/CIRR#Annotations) of the README in the CIRR dataset repo.
